### ISSUE TITLE
Vectorize a batch of images at the same time?

### ISSUE THREAD

**Issue by oOHeavenOo** [chenmingxiang110/AugNet#1]
Hi! It took me a while to find this project. There are only a limited number of examples of using image vectorization to calculate similarities, and this project looks great, but there are also imperfections.

I installed the package via pip and everything works fine, except that I can only vectorize one image at a time, which is inefficient. Can you provide a function so that we can vectorize a bunch of images with one call? Thank you!

**Comment by chenmingxiang110** [comment]
Hello oOHeavenOo. Thank you very much for your advice. I will add the batch vectorization function in the next update.

**Comment by chenmingxiang110** [comment]
Hi oOHeavenOo. The function is added. Now you can feed a batch of images to the "vectorize" function. Feel free to download the latest pip package.

**Comment by oOHeavenOo** [comment]
Great. Thanks!
