### ISSUE TITLE
Would you please release training script on imagenet?

### ISSUE THREAD

**Issue by CoinCheung** [chenmingxiang110/AugNet#3]
Hi,

I would like to try this method on a large dataset, would you please release the script you used to train on the imagenet?

**Comment by chenmingxiang110** [comment]
Yes sure. I will reply to this issue once updated.

**Comment by chenmingxiang110** [comment]
Hi, I have uploaded the script (res50_model_training_with_ImageNet.py) to train on imagenet. Make sure to check line 38 and 39 to set the path of your imagenet folder, and where do you want the model to be saved at. Have fun!

**Comment by CoinCheung** [comment]
Thanks a lot, I am closing this.

**Comment by CoinCheung** [comment]
Hi,

Would you please tell me, how many epoches have you trained resnet50 on imagenet? By the way, did you observe a trend that the more epoches to train the model, the better the performance is?
